### ISSUE TITLE
puppet-rundeck not working with puppet 3.0 RC6

### ISSUE THREAD

**Issue by cosminilie** [jamtur01/puppet-rundeck#11]
I've installed this module with puppet master 3.0 RC6 however even though i have facts for two hosts the xml is empty :

[]# curl localhost:8144
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "-//DTO Labs Inc.//DTD Resources Document 1.0//EN" "project.dtd">
<project>

**Comment by jamtur01** [comment]
No error output anywhere?

**Comment by cosminilie** [comment]
Nothing. No error message. 

Cosmin Ilie | Synygy Inc | T: +40.758.035354 | cosmin_ilie@live.com | http://cosminilie.ro

Chat MSN: cosmin_ilie@live.com

Contact Me 

Date: Fri, 21 Sep 2012 04:37:41 -0700

**Comment by jamtur01** [comment]
I am working on this currently. The source of the data has changed in 3.0.

**Comment by staggmeister** [comment]
Hi !

I have the same issue with puppet 3.4.3 Open Source. 
My Puppetmaster is on Ubuntu 14.04 such as the rundeck server (2.1.0)

Do you know how i could fix that problem ?

Thanks

PS: i'm french student and i know i've really bad english. so sorry !

**Comment by jamtur01** [comment]
Try the current master.

**Comment by staggmeister** [comment]
Hi !

Thanks for your answer, i've installed the curent puppetmaster (3.6.2) with passenger/apache ; puppetdb (2.1) and dashboard (2.0).

I ran gem install puppet-rundeck
and puppet-rundeck such as you said

All that crap works almost, just a little issue with inventory service.

When i go at : localhost:8144
I've got that error :

NoMethodError at /
undefined method `to_xs' for "<myserver.fqdn>":String
file: puppet-rundeck.rb location: xml_escape line: 41

rake logger :
#<Rack::NullLogger:0x96f3ea8 @app=#<Rack::Protection::FrameOptions:0x96f3fe8 @app=#<Rack::Protection::HttpOrigin:0x96f404c @app=#<Rack::Protection::IPSpoofing:0x96f413c @app=#<Rack::Protection::JsonCsrf:0x96f4204 @app=#<Rack::Protection::PathTraversal:0x96f42a4 @app=#<Rack::Protection::XSSHeader:0x96f436c @app=#<PuppetRundeck:0x969f448 @default_layout=:layout, @preferred_extension=nil, @app=nil, @template_cache=#<Tilt::Cache:0x969f45c @cache={}>>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :xss_mode=>:block, :nosniff=>true, :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :except=>[:session_hijacking, :remote_token]}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml"], :frame_options=>:sameorigin, :except=>[:session_hijacking, :remote_token]}, @frame_options="SAMEORIGIN">>

trace :

NoMethodError: undefined method `to_xs' for "<myserver.fqdn>":String
    /var/lib/gems/1.9.1/gems/puppet-rundeck-0.0.7/lib/puppet-rundeck.rb:41:in`xml_escape'
    /var/lib/gems/1.9.1/gems/puppet-rundeck-0.0.7/lib/puppet-rundeck.rb:66:in `block (2 levels) in <class:PuppetRundeck>'
    /var/lib/gems/1.9.1/gems/puppet-rundeck-0.0.7/lib/puppet-rundeck.rb:57:in`each'
    /var/lib/gems/1.9.1/gems/puppet-rundeck-0.0.7/lib/puppet-rundeck.rb:57:in `block in <class:PuppetRundeck>'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in`call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in`[]'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in`route_eval'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in`block in process_route'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in`process_route'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in`each'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in`block in dispatch!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in`catch'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in`dispatch!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in`block in invoke'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in`invoke'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in`call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in`call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in`call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in`call'
    /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
    /var/lib/gems/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in`call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in`call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in`block in call'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
    /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in`call'
    /var/lib/gems/1.9.1/gems/thin-1.6.2/lib/thin/connection.rb:86:in `block in pre_process'
    /var/lib/gems/1.9.1/gems/thin-1.6.2/lib/thin/connection.rb:84:in`catch'
    /var/lib/gems/1.9.1/gems/thin-1.6.2/lib/thin/connection.rb:84:in `pre_process'
    /var/lib/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in`call'
    /var/lib/gems/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `block in spawn_threadpool'

Do you know how i could fix that problem ?

thanks

**Comment by jamtur01** [comment]
Fixed in latest release - 0.0.9.
