### ISSUE TITLE
can't run puppet-rundeck with puppet enterprise version 2.7

### ISSUE THREAD

**Issue by dokhodai** [jamtur01/puppet-rundeck#15]
Hi,
I just installed puppet-rundeck module on my puppet master server. I tried to run puppet-rundeck and got this error. any idea?

You need to have Puppet 0.25.5 or later installed
/usr/lib/ruby/gems/1.8/gems/puppet-rundeck-0.0.7/lib/puppet-rundeck.rb:34:in `co
nfigure': uninitialized constant Class::Puppet (NameError)
        from /usr/lib/ruby/gems/1.8/gems/puppet-rundeck-0.0.7/bin/puppet-rundeck
:62
        from /usr/bin/puppet-rundeck:19:in`load'
        from /usr/bin/puppet-rundeck:19

my puppet master version:
Puppet v2.7.19 (Puppet Enterprise 2.7.0)

**Comment by jamtur01** [comment]
This functionality is broken with recent Puppet versions and I've never tested it with PE so it could well be busted. I need to revisit this whole tool but haven't had time recently. I'll try to take a look in the next few weeks.

**Comment by dokhodai** [comment]
thanks for a quick responded. I am looking forward to the next release.

**Comment by 9901310169** [comment]
Hi jamtur,

 I just installed puppet & puppet-rundeck plugin on puppet server.After that i tried to run puppet-rundeck,got this error.........

  You need to have Puppet 0.25.5 or later installed
/usr/lib64/ruby/gems/1.8/gems/puppet-rundeck-0.0.7/lib/puppet-rundeck.rb:34:in `configure': uninitialized constant Class::Puppet (NameError)
        from /usr/lib64/ruby/gems/1.8/gems/puppet-rundeck-0.0.7/bin/puppet-rundeck:62
        from /usr/bin/puppet-rundeck:19:in`load'
        from /usr/bin/puppet-rundeck:19

My puppet is
 puppet --version
2.7.19 (Puppet Enterprise 2.7.0)

**Comment by mmlumba** [comment]
Hi jamtur,
Is there an update on this issue? I am running an even newer version of Puppet (3.2.3) and I have been getting this error.
Thanks

**Comment by jamtur01** [comment]
I've not had any time to look at this and since I don't use Puppet much anymore it's unlikely I will get said time. Sorry. :(

**Comment by jamtur01** [comment]
I've just merged some updates - try the current master.

**Comment by jamtur01** [comment]
Should be fixed in 0.0.9.
