### ISSUE TITLE
can't run puppet rundeck

### ISSUE THREAD

**Issue by roquesao** [jamtur01/puppet-rundeck#17]
when trying to execute it I'm getting this error:

puppet-rundeck
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': /usr/lib/ruby/gems/1.8/gems/sinatra-1.4.2/lib/sinatra/base.rb:1913: syntax error (SyntaxError)
        define_method(method_name) do |*args, &block|
                                             ^
/usr/lib/ruby/gems/1.8/gems/sinatra-1.4.2/lib/sinatra/base.rb:1914: syntax error
          return super(*args, &block) if respond_to? method_name
                      ^
/usr/lib/ruby/gems/1.8/gems/sinatra-1.4.2/lib/sinatra/base.rb:1977: syntax error    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /usr/lib/ruby/gems/1.8/gems/puppet-rundeck-0.0.4/lib/puppet-rundeck.rb:17
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from /usr/lib/ruby/gems/1.8/gems/puppet-rundeck-0.0.4/bin/puppet-rundeck:22
    from /usr/bin/puppet-rundeck:19:in `load'
    from /usr/bin/puppet-rundeck:19
You have new mail in /var/spool/mail/root

do you have any clue ?

**Comment by jamtur01** [comment]
That seems like a Sinatra issue rather than a puppet-rundeck one.
