### ISSUE TITLE
Please add documentation about adding tags in puppet

### ISSUE THREAD

**Issue by jdmulloy** [jamtur01/puppet-rundeck#21]
Can you please add a little bit to the Readme about how to add tags in Puppet so that puppet-rundeck can pick them up? I've done quite a bit of searching on the internet and I can't figure out how to do it.

**Comment by tdelphi** [comment]
Same problem. It's probably not the issue of puppet-rundeck, but problem of puppet project itself. 
Btw, there is information about adding tags to classes and resources, but these tags are not available to puppet-rundeck (and probably to puppetmaster itself?).

**Comment by jamtur01** [comment]
This is more a Puppet issue.
