### ISSUE TITLE
puppet-rundeck errors out with NoMethodError - undefined method `to_xs'

### ISSUE THREAD

**Issue by tvc123** [jamtur01/puppet-rundeck#26]
I followed the instructions and installed puppet-rundeck with gem install puppet-rundeck.  Everything installed fine but when I go to request the list I get the following error
`[2014-08-12 09:56:06] INFO  WEBrick::HTTPServer#start: pid=25033 port=8144
NoMethodError - undefined method`to_xs' for "xxx-yyy.xxx.xxx.com":String:
        /var/lib/gems/1.9.1/gems/puppet-rundeck-0.0.7/lib/puppet-rundeck.rb:41:in `xml_escape'
        /var/lib/gems/1.9.1/gems/puppet-rundeck-0.0.7/lib/puppet-rundeck.rb:66:in`block (2 levels) in class:PuppetRundeck'`

I am running ubuntu 14.4 with Puppet and Foreman installed on the host.

**Comment by jamtur01** [comment]
You you please try the newly released 0.0.8 version.

**Comment by tvc123** [comment]
with 0.0.8 I get the following
NoMethodError - undefined method `values' for
#Puppet::Node:0x00000003078570:

/var/lib/gems/1.9.1/gems/puppet-rundeck-0.0.8/lib/puppet-rundeck.rb:66:in
`block (2 levels) in class:PuppetRundeck'

/var/lib/gems/1.9.1/gems/puppet-rundeck-0.0.8/lib/puppet-rundeck.rb:60:in
`each'

/var/lib/gems/1.9.1/gems/puppet-rundeck-0.0.8/lib/puppet-rundeck.rb:60:in
`block in <class:PuppetRundeck>'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in
`call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in
`block in compile!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in
`[]'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in
`block (3 levels) in route!'

**Comment by jamtur01** [comment]
What version of Puppet are you running?

**Comment by tvc123** [comment]
puppet --version
3.6.2

**Comment by jamtur01** [comment]
Okay - try 0.0.9 which I just pushed that replaced builder with fast_xs. That should resolve the issue. Apologies. This code doesn't get maintained much and I don't use Puppet much anymore.

**Comment by tvc123** [comment]
Thank you that resolves the issue!
