### ISSUE TITLE
Gem installation failed

### ISSUE THREAD

**Issue by ypodo** [jamtur01/puppet-rundeck#29]
I am filed to install the gem "**puppet-rundeck**"

operatingsystem => CentOS
operatingsystemmajrelease => 7
operatingsystemrelease => 7.3.1611
puppetversion => 4.8.2

**gem install puppet-rundeck**
Building native extensions.  This could take a while...
ERROR:  Error installing puppet-rundeck:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
checking for assert.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib64
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/ruby
/usr/share/ruby/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/share/ruby/mkmf.rb:565:in `try_cpp'
        from /usr/share/ruby/mkmf.rb:1038:in `block in have_header'
        from /usr/share/ruby/mkmf.rb:889:in `block in checking_for'
        from /usr/share/ruby/mkmf.rb:340:in `block (2 levels) in postpone'
        from /usr/share/ruby/mkmf.rb:310:in `open'
        from /usr/share/ruby/mkmf.rb:340:in `block in postpone'
        from /usr/share/ruby/mkmf.rb:310:in `open'
        from /usr/share/ruby/mkmf.rb:336:in `postpone'
        from /usr/share/ruby/mkmf.rb:888:in `checking_for'
        from /usr/share/ruby/mkmf.rb:1037:in `have_header'
        from extconf.rb:2:in `<main>'

Gem files will remain installed in /usr/local/share/gems/gems/fast_xs-0.8.0 for inspection.
Results logged to /usr/local/share/gems/gems/fast_xs-0.8.0/ext/fast_xs/gem_make.out

**Comment by jamtur01** [comment]
You don't have development tools installed as per the error  message. On Centos that probably something like:

```
yum install ruby ruby-devel ruby-ri ruby-rdoc gcc gcc-c++ automake autoconf make
```
