### ISSUE TITLE
Puppet::Error  Could not find class

### ISSUE THREAD

**Issue by lrhazi** [jamtur01/puppet-rundeck#4]
I get a 500 Error with this exception when I try this module:

Puppet::Error - Could not find class gu_modules for uis-cesia-1.example.com on node uis-cesia-1.example.com :

How can I debug to find the root cause?

All my modules are in per environment tree, as follows, could this be the problem?

[master]
    templatedir = /etc/puppet/environments/$environment/
    modulepath  = /etc/puppet/environments/$environment/modules
    manifest    = /etc/puppet/environments/$environment/manifests/site.pp
    manifestdir = /etc/puppet/environments/$environment/manifests

Thanks.

**Comment by lrhazi** [comment]
The full stack:

Puppet::Error - Could not find class gu_modules for uis-cesia-1.example.comon node uis-cesia-1.example.com:
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-2.7.6/lib/puppet/parser/compiler.rb:27:in `compile'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-2.7.6/lib/puppet/indirector/catalog/compiler.rb:77:in`compile'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-2.7.6/lib/puppet/util.rb:185:in `benchmark'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-2.7.6/lib/puppet/indirector/catalog/compiler.rb:75:in`compile'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-2.7.6/lib/puppet/indirector/catalog/compiler.rb:35:in `find'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-2.7.6/lib/puppet/indirector/indirection.rb:189:in`find'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-rundeck-0.0.5/lib/puppet-rundeck.rb:62:in `GET /'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-rundeck-0.0.5/lib/puppet-rundeck.rb:56:in`each'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-rundeck-0.0.5/lib/puppet-rundeck.rb:56:in `GET /'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1211:in`call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1211:in `compile!'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in`[]'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `route!'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:788:in`route_eval'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:772:in `route!'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:821:in`process_route'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in `catch'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:819:in`process_route'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:771:in `route!'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in`each'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:770:in `route!'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:886:in`dispatch!'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in `call!'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in`invoke'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in `catch'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:871:in`invoke'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:706:in `call!'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:692:in`call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in `call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/path_traversal.rb:16:in`call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/json_csrf.rb:17:in `call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/base.rb:47:in`call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rack-protection-1.1.4/lib/rack/protection/xss_header.rb:22:in `call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/nulllogger.rb:9:in`call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/head.rb:9:in `call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/showexceptions.rb:21:in`call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1403:in`synchronize'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1334:in `call'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/handler/webrick.rb:59:in`service'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:162:in`start'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:95:in`start'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:92:in `each'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:92:in`start'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:23:in `start'
        /opt/ruby-enterprise/lib/ruby/1.8/webrick/server.rb:82:in`start'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/rack-1.3.5/lib/rack/handler/webrick.rb:13:in `run'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/sinatra-1.3.1/lib/sinatra/base.rb:1295:in`run!'
        /opt/ruby-enterprise/lib/ruby/gems/1.8/gems/puppet-rundeck-0.0.5/bin/puppet-rundeck:63
        /opt/ruby-enterprise/bin/puppet-rundeck:19:in `load'
        /opt/ruby-enterprise/bin/puppet-rundeck:19

**Comment by jamtur01** [comment]
I don't think this has anything to do with Puppet Rundeck.  I suspect this is a Puppet error being presented up. Do you see this at all in your Puppet runs?

**Comment by lrhazi** [comment]
Nope. I went to the specific node being complained about and did a puppet run and it succeeds with no errors!

**Comment by lrhazi** [comment]
Where can I increase debugging level in Puppet and/or in Puppet Rundeck, so as to see more into the issue?

Thanks a lot.
Mohamed.

**Comment by lrhazi** [comment]
And I am using a custom ENC script... is that the problem you think?

**Comment by lrhazi** [comment]
I puts a few "puts" to figure out where it breaks. Narrowed it down to the tags lines.
I removed lines 60, 63 and 74, and it works now.

I don't think I have any tags defined in my manifests... is that causing it to fail?

**Comment by jamtur01** [comment]
Tags are automatically added - so even if you don't define any there still should be some.  I'll do some testing tonight.  I am leaning towards an ENC error but it's odd output.

**Comment by jamtur01** [comment]
This is fixed. Looks like the method for grabbing tags is broken. For the moment I'm just grabbing environment.
