### ISSUE TITLE
No longer returning multiple tags.

### ISSUE THREAD

**Issue by sirhopcount** [jamtur01/puppet-rundeck#7]
Hi,

We are currently deploying puppet-rundeck in our production environment but we are running in to a small problem. There seems to be a regression ever since commit b129c72. Before this commit puppet-rundeck would also return tags assigned to a node. The current version just returns the environment variable as a tag.

It was our intention to configure our rundeck node filters based on the tags provided by puppet to rundeck via puppet-rundeck. Was this feature changed to remove the dependency on puppet or is this a bug ?

Regards,

Adrian.

**Comment by jamtur01** [comment]
This is fixed in 0.0.8.
